### PR TITLE
About/membership/ashley

### PR DESCRIPTION
**Pull request by ashlxyzhang**

### CODE REVIEW

**Comment by peicasey** [comment]
change to have officer info in a json

**Review by peicasey — COMMENTED** [review]
the major thing is inconsistent, some BMEN others not the acronym, so I think it would be better to switch to the full major name

It would also be nice if people were grouped together -- so execs in the same section, then for regular officers by their branch

also some updates, i think more people submitted their stuff + summer transferred to cs! :D

**Comment by LarissaNamu** [comment]
the image showing membership details is a bit fuzzy - (attached picture is what im seeing), 
pic1

**Review by peicasey — APPROVED** [review]
Looks good, make a new branch for all the officers being in the same box + add missing officers who didn't submit info

**Pull request merged**
